#!/usr/bin/env python3
"""Generate the per-locale `MarketingSeed.strings` tables.

Source of truth for the DEBUG-only marketing screenshot seed copy used by
`OwloryUITestSupport.seedMarketing`. This is a SEPARATE strings table from the
app's `Localizable.strings` UI catalog: intentionally NOT part of that catalog's
parity checks or native-review pipeline, so localizing screenshot fixtures never
disturbs the 100%-native-reviewed UI strings.

Translations are LLM-drafted (pending optional native review on the marketing
track) and stored as lists aligned to SOURCE order — index alignment avoids the
key-typo risk of repeating ~900 English keys. A blank entry (or a locale not yet
filled) falls back to the English source string; `seedMarketing` also passes the
English `value:` so a missing table still renders English rather than raw keys.

Run:
    python3 Tools/marketing-seed-strings-generate.py
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RESOURCES = REPO_ROOT / "owlory_xcode/Owlory/Resources"

LOCALES = ["en", "ar", "nl", "fr", "de", "it", "ja", "ko", "nb", "pt",
           "pt-BR", "ru", "es", "sv", "zh-Hans", "zh-Hant", "tr", "uk", "vi"]

# Ordered English source strings == lookup keys (mirror seedMarketing literals).
SOURCE: list[str] = [
    "Finalize Q4 1:1 notes for direct reports",
    "30-min easy run before dinner",
    "Pick up dry cleaning by 6 pm",
    "Draft sprint retro talking points",
    "Strength: legs (3x8)",
    "Pay quarterly tax estimate",
    "Pull together onboarding metrics review",
    "5K easy run",
    "Schedule dentist appointment",
    "Felt scattered — meetings ate the morning. Plan deep work earlier.",
    "Energy held through evening. Run cleared the mental fog.",
    "Hit all three. Good rhythm. Sleep mattered.",
    "Lost momentum after lunch. Try lighter midday meal.",
    "Best day this week. Protected morning paid off.",
    "Solid. Career review prep moving the needle.",
    "Idea: weekly batch errands on Saturdays",
    "Group DMV, dry cleaning, hardware-store loops into one Saturday block. Test for 3 weeks.",
    "Watch: SwiftUI navigation patterns talk",
    "WWDC25 session on programmatic navigation. Compare NavigationStack vs SplitView trade-offs.",
    "Onboarding redesign — one-pager",
    "Problem: 41% of new users never reach Focus Three on day one. Hypothesis: reduce the capture-vs-plan choice during day 1. Test variant A swaps the empty-state to suggest 3 sample focus items.",
    "Career conversation prep with manager",
    "Topics: scope expansion, mentorship of new hires, Q1 OKRs alignment. Win to lead with: shipped onboarding A/B with +12% activation.",
    "Insight: deep work blocks shrink without protection",
    "Three consecutive weeks where morning blocks were broken by reactive Slack — output dropped measurably. Calendar the 9-11 block as immovable starting next week.",
    "Slept well. Light soreness from yesterday's run.",
    "5.2K easy run, 27 min",
    "Steady pace, breath in control. Could have pushed last K.",
    "Yoga: hip mobility",
    "Yoga: hip mobility (35 min flow)",
    "Hips opening. Add this twice a week instead of one.",
    "Sunday meal prep",
    "Plan menu for the week",
    "Inventory pantry + write list",
    "Shop within 60 min",
    "Cook proteins + grains in bulk",
    "Portion lunches into 5 containers",
    "Take out recycling",
    "Bin out before Tuesday 6 am pickup.",
    "Refill dish soap",
    "Six-month checkup overdue by two weeks.",
    "Federal + state. Due 15th.",
    "Career follow-through climbed with protected morning blocks; energy dipped on the day with the lightest sleep.",
    "Shipped onboarding redesign A/B test",
    "Variant A (sample focus suggestions in empty state) launched to 50% of new users. Day-1 activation lifted +12% over control across the first 2,000 cohorts.",
    "+12% activation; n=2,134",
    "Led migration kickoff with three teams",
    "Aligned backend, mobile, and platform on the schema migration plan. Walked through the rollback path, owners, and acceptance gates. No open blockers exiting the meeting.",
    "3 teams aligned; 0 blockers",
]

# LLM-drafted translations, aligned 1:1 with SOURCE order.
TRANSLATIONS: dict[str, list[str]] = {
    "de": [
        "Q4-Mitarbeitergespräch-Notizen finalisieren",
        "30-Min. lockerer Lauf vor dem Abendessen",
        "Reinigung bis 18 Uhr abholen",
        "Stichpunkte für Sprint-Retro entwerfen",
        "Kraft: Beine (3×8)",
        "Quartalssteuer-Vorauszahlung leisten",
        "Onboarding-Kennzahlen-Review zusammenstellen",
        "5 km lockerer Lauf",
        "Zahnarzttermin vereinbaren",
        "Zerstreut gefühlt – Meetings haben den Vormittag verschluckt. Tiefenarbeit früher einplanen.",
        "Energie hielt bis zum Abend. Der Lauf vertrieb den Nebel im Kopf.",
        "Alle drei geschafft. Guter Rhythmus. Schlaf war entscheidend.",
        "Nach dem Mittag den Schwung verloren. Leichteres Mittagessen versuchen.",
        "Bester Tag diese Woche. Der geschützte Vormittag hat sich gelohnt.",
        "Solide. Die Vorbereitung aufs Karrieregespräch bringt etwas.",
        "Idee: Besorgungen samstags wöchentlich bündeln",
        "Behördengänge, Reinigung und Baumarkt-Wege in einen Samstagsblock bündeln. 3 Wochen testen.",
        "Ansehen: Vortrag zu SwiftUI-Navigationsmustern",
        "WWDC25-Session zu programmatischer Navigation. NavigationStack vs. SplitView abwägen.",
        "Onboarding-Redesign – Einseiter",
        "Problem: 41 % der neuen Nutzer erreichen am ersten Tag nie die Fokus-Drei. Hypothese: die Erfassen-oder-Planen-Entscheidung an Tag 1 reduzieren. Testvariante A ersetzt den Leerzustand durch 3 Beispiel-Fokuspunkte.",
        "Vorbereitung aufs Karrieregespräch mit der Führungskraft",
        "Themen: Verantwortungsausweitung, Mentoring neuer Mitarbeiter, Abstimmung der Q1-OKRs. Erfolg zum Einstieg: Onboarding-A/B mit +12 % Aktivierung ausgeliefert.",
        "Erkenntnis: Tiefenarbeitsblöcke schrumpfen ohne Schutz",
        "Drei Wochen in Folge wurden die Vormittagsblöcke durch reaktives Slack zerrissen – die Leistung sank messbar. Ab nächster Woche den Block von 9–11 Uhr als unverrückbar eintragen.",
        "Gut geschlafen. Leichter Muskelkater vom gestrigen Lauf.",
        "5,2 km lockerer Lauf, 27 Min.",
        "Gleichmäßiges Tempo, Atmung unter Kontrolle. Beim letzten Kilometer wäre mehr drin gewesen.",
        "Yoga: Hüftmobilität",
        "Yoga: Hüftmobilität (35-Min.-Flow)",
        "Hüften öffnen sich. Künftig zweimal statt einmal pro Woche einbauen.",
        "Sonntags-Meal-Prep",
        "Wochenmenü planen",
        "Vorräte prüfen + Liste schreiben",
        "In 60 Min. einkaufen",
        "Proteine + Beilagen in großer Menge kochen",
        "Mittagessen auf 5 Behälter portionieren",
        "Wertstoffe rausbringen",
        "Tonne vor der Abholung am Dienstag um 6 Uhr rausstellen.",
        "Spülmittel nachfüllen",
        "Halbjahres-Kontrolle seit zwei Wochen überfällig.",
        "Bund + Land. Fällig am 15.",
        "Die Karriere-Konsequenz stieg mit geschützten Vormittagsblöcken; die Energie sank am Tag mit dem wenigsten Schlaf.",
        "Onboarding-Redesign-A/B-Test ausgeliefert",
        "Variante A (Beispiel-Fokusvorschläge im Leerzustand) an 50 % der neuen Nutzer ausgerollt. Die Tag-1-Aktivierung stieg über die ersten 2.000 Kohorten um +12 % gegenüber der Kontrolle.",
        "+12 % Aktivierung; n=2.134",
        "Migrations-Kickoff mit drei Teams geleitet",
        "Backend, Mobile und Plattform auf den Schema-Migrationsplan abgestimmt. Rollback-Pfad, Verantwortliche und Abnahmekriterien durchgegangen. Keine offenen Blocker nach dem Meeting.",
        "3 Teams abgestimmt; 0 Blocker",
    ],
    "fr": [
        "Finaliser les notes des points individuels du T4",
        "Course tranquille de 30 min avant le dîner",
        "Récupérer le pressing avant 18 h",
        "Rédiger les points de la rétro de sprint",
        "Renforcement : jambes (3×8)",
        "Payer l'acompte d'impôt trimestriel",
        "Compiler la revue des métriques d'onboarding",
        "Course tranquille de 5 km",
        "Prendre rendez-vous chez le dentiste",
        "Journée dispersée — les réunions ont mangé la matinée. Planifier le travail de fond plus tôt.",
        "L'énergie a tenu jusqu'au soir. La course a dissipé le brouillard mental.",
        "Les trois faits. Bon rythme. Le sommeil a compté.",
        "Élan perdu après le déjeuner. Essayer un repas plus léger à midi.",
        "Meilleur jour de la semaine. La matinée protégée a payé.",
        "Solide. La prépa de l'entretien de carrière avance.",
        "Idée : regrouper les courses le samedi chaque semaine",
        "Regrouper préfecture, pressing et magasin de bricolage en un seul créneau le samedi. Tester 3 semaines.",
        "À voir : conférence sur les schémas de navigation SwiftUI",
        "Session WWDC25 sur la navigation programmatique. Comparer NavigationStack et SplitView.",
        "Refonte de l'onboarding — note d'une page",
        "Problème : 41 % des nouveaux utilisateurs n'atteignent jamais les Trois Priorités le premier jour. Hypothèse : réduire le choix capturer/planifier au jour 1. La variante A remplace l'état vide par 3 exemples de priorités.",
        "Préparer l'entretien de carrière avec le manager",
        "Sujets : élargissement du périmètre, mentorat des nouvelles recrues, alignement des OKR du T1. Réussite à mettre en avant : A/B d'onboarding livré avec +12 % d'activation.",
        "Constat : les blocs de travail de fond rétrécissent sans protection",
        "Trois semaines d'affilée où les blocs du matin ont été brisés par Slack réactif — la production a chuté de façon mesurable. Bloquer le créneau 9 h–11 h comme inamovible dès la semaine prochaine.",
        "Bien dormi. Légères courbatures de la course d'hier.",
        "Course tranquille de 5,2 km, 27 min",
        "Allure régulière, souffle maîtrisé. J'aurais pu pousser sur le dernier km.",
        "Yoga : mobilité des hanches",
        "Yoga : mobilité des hanches (flow de 35 min)",
        "Les hanches s'ouvrent. À intégrer deux fois par semaine plutôt qu'une.",
        "Batch cooking du dimanche",
        "Planifier le menu de la semaine",
        "Inventorier le garde-manger + faire la liste",
        "Faire les courses en 60 min",
        "Cuire protéines + féculents en grande quantité",
        "Répartir les déjeuners dans 5 contenants",
        "Sortir le tri sélectif",
        "Sortir la poubelle avant la collecte du mardi à 6 h.",
        "Recharger le liquide vaisselle",
        "Bilan semestriel en retard de deux semaines.",
        "Fédéral + régional. Échéance le 15.",
        "Le suivi de carrière a progressé avec des matinées protégées ; l'énergie a baissé le jour où le sommeil a été le plus court.",
        "Test A/B de refonte de l'onboarding livré",
        "Variante A (suggestions de priorités dans l'état vide) déployée auprès de 50 % des nouveaux utilisateurs. L'activation au jour 1 a progressé de +12 % par rapport au témoin sur les 2 000 premières cohortes.",
        "+12 % d'activation ; n=2 134",
        "Lancement de la migration piloté avec trois équipes",
        "Backend, mobile et plateforme alignés sur le plan de migration du schéma. Revue du plan de rollback, des responsables et des critères d'acceptation. Aucun blocage à la sortie de la réunion.",
        "3 équipes alignées ; 0 blocage",
    ],
    "es": [
        "Finalizar las notas de los 1:1 del T4",
        "Carrera suave de 30 min antes de cenar",
        "Recoger la tintorería antes de las 18:00",
        "Redactar los puntos de la retro del sprint",
        "Fuerza: piernas (3×8)",
        "Pagar el anticipo trimestral de impuestos",
        "Preparar la revisión de métricas de onboarding",
        "Carrera suave de 5 km",
        "Pedir cita con el dentista",
        "Día disperso: las reuniones se comieron la mañana. Planear el trabajo profundo antes.",
        "La energía aguantó hasta la noche. La carrera despejó la niebla mental.",
        "Logré las tres. Buen ritmo. El sueño importó.",
        "Perdí impulso tras la comida. Probar un almuerzo más ligero.",
        "El mejor día de la semana. La mañana protegida valió la pena.",
        "Sólido. La preparación de la conversación de carrera avanza.",
        "Idea: agrupar los recados los sábados cada semana",
        "Agrupar tráfico, tintorería y ferretería en un solo bloque el sábado. Probar 3 semanas.",
        "Ver: charla sobre patrones de navegación en SwiftUI",
        "Sesión de la WWDC25 sobre navegación programática. Comparar NavigationStack y SplitView.",
        "Rediseño del onboarding: resumen de una página",
        "Problema: el 41 % de los nuevos usuarios nunca llega a las Tres Prioridades el primer día. Hipótesis: reducir la decisión capturar/planificar el día 1. La variante A cambia el estado vacío por 3 prioridades de ejemplo.",
        "Preparar la conversación de carrera con el responsable",
        "Temas: ampliación de alcance, mentoría de nuevas incorporaciones, alineación de OKR del T1. Logro para empezar: A/B de onboarding lanzado con +12 % de activación.",
        "Hallazgo: los bloques de trabajo profundo se encogen sin protección",
        "Tres semanas seguidas en que Slack reactivo rompió los bloques de la mañana: la productividad cayó de forma medible. Bloquear de 9 a 11 como inamovible desde la próxima semana.",
        "Dormí bien. Ligeras agujetas de la carrera de ayer.",
        "Carrera suave de 5,2 km, 27 min",
        "Ritmo constante, respiración controlada. Podría haber apretado en el último km.",
        "Yoga: movilidad de cadera",
        "Yoga: movilidad de cadera (flujo de 35 min)",
        "Las caderas se abren. Incluirlo dos veces por semana en vez de una.",
        "Preparación de comidas del domingo",
        "Planificar el menú de la semana",
        "Revisar la despensa + hacer la lista",
        "Comprar en 60 min",
        "Cocinar proteínas + cereales en grandes cantidades",
        "Repartir los almuerzos en 5 recipientes",
        "Sacar el reciclaje",
        "Sacar el cubo antes de la recogida del martes a las 6:00.",
        "Rellenar el jabón lavavajillas",
        "Revisión semestral atrasada dos semanas.",
        "Federal + estatal. Vence el día 15.",
        "El seguimiento de carrera subió con mañanas protegidas; la energía bajó el día con menos sueño.",
        "Lanzado el test A/B del rediseño de onboarding",
        "Variante A (sugerencias de prioridades en el estado vacío) lanzada al 50 % de los nuevos usuarios. La activación del día 1 subió +12 % frente al control en las primeras 2.000 cohortes.",
        "+12 % de activación; n=2134",
        "Dirigí el arranque de la migración con tres equipos",
        "Backend, móvil y plataforma alineados en el plan de migración del esquema. Repasamos el plan de reversión, los responsables y los criterios de aceptación. Sin bloqueos al salir de la reunión.",
        "3 equipos alineados; 0 bloqueos",
    ],
    "it": [
        "Finalizzare le note dei 1:1 del Q4",
        "Corsa leggera di 30 min prima di cena",
        "Ritirare la lavanderia entro le 18",
        "Stendere i punti della retro di sprint",
        "Forza: gambe (3×8)",
        "Pagare l'acconto fiscale trimestrale",
        "Mettere insieme la revisione delle metriche di onboarding",
        "Corsa leggera di 5 km",
        "Fissare l'appuntamento dal dentista",
        "Giornata dispersiva: le riunioni hanno mangiato la mattina. Pianificare prima il lavoro profondo.",
        "L'energia ha retto fino a sera. La corsa ha dissolto la nebbia mentale.",
        "Fatte tutte e tre. Buon ritmo. Il sonno ha contato.",
        "Slancio perso dopo pranzo. Provare un pranzo più leggero.",
        "Giornata migliore della settimana. La mattina protetta ha pagato.",
        "Solido. La preparazione del colloquio di carriera procede.",
        "Idea: raggruppare le commissioni il sabato ogni settimana",
        "Raggruppare motorizzazione, lavanderia e ferramenta in un unico blocco il sabato. Provare per 3 settimane.",
        "Da vedere: talk sui pattern di navigazione in SwiftUI",
        "Sessione WWDC25 sulla navigazione programmatica. Confrontare NavigationStack e SplitView.",
        "Riprogettazione dell'onboarding — one-pager",
        "Problema: il 41 % dei nuovi utenti non raggiunge mai le Tre Priorità il primo giorno. Ipotesi: ridurre la scelta cattura/pianifica nel giorno 1. La variante A sostituisce lo stato vuoto con 3 priorità di esempio.",
        "Preparare il colloquio di carriera con il responsabile",
        "Temi: ampliamento del ruolo, mentoring dei nuovi assunti, allineamento OKR del Q1. Risultato da cui partire: A/B di onboarding rilasciato con +12 % di attivazione.",
        "Intuizione: i blocchi di lavoro profondo si riducono senza protezione",
        "Tre settimane di fila in cui i blocchi del mattino sono stati spezzati da Slack reattivo: la produttività è calata in modo misurabile. Bloccare la fascia 9–11 come inamovibile dalla prossima settimana.",
        "Dormito bene. Lievi indolenzimenti dalla corsa di ieri.",
        "Corsa leggera di 5,2 km, 27 min",
        "Passo costante, respiro sotto controllo. Potevo spingere sull'ultimo km.",
        "Yoga: mobilità dell'anca",
        "Yoga: mobilità dell'anca (flow di 35 min)",
        "Le anche si aprono. Inserirlo due volte a settimana invece di una.",
        "Meal prep della domenica",
        "Pianificare il menù della settimana",
        "Controllare la dispensa + scrivere la lista",
        "Fare la spesa in 60 min",
        "Cucinare proteine + cereali in grande quantità",
        "Dividere i pranzi in 5 contenitori",
        "Portare fuori la raccolta differenziata",
        "Mettere fuori il bidone prima del ritiro di martedì alle 6.",
        "Ricaricare il detersivo per piatti",
        "Controllo semestrale in ritardo di due settimane.",
        "Federale + regionale. Scadenza il 15.",
        "La costanza sulla carriera è cresciuta con mattine protette; l'energia è calata nel giorno con meno sonno.",
        "Rilasciato il test A/B della riprogettazione dell'onboarding",
        "Variante A (suggerimenti di priorità nello stato vuoto) rilasciata al 50 % dei nuovi utenti. L'attivazione al giorno 1 è salita del +12 % rispetto al controllo sulle prime 2.000 coorti.",
        "+12 % di attivazione; n=2.134",
        "Guidato il kickoff della migrazione con tre team",
        "Backend, mobile e piattaforma allineati sul piano di migrazione dello schema. Rivisti percorso di rollback, responsabili e criteri di accettazione. Nessun blocco all'uscita dalla riunione.",
        "3 team allineati; 0 blocchi",
    ],
    "pt": [
        "Finalizar as notas das reuniões individuais do 4.º trimestre",
        "Corrida leve de 30 min antes do jantar",
        "Levantar a roupa da lavandaria até às 18h",
        "Redigir os tópicos da retro do sprint",
        "Força: pernas (3×8)",
        "Pagar o pagamento por conta trimestral",
        "Reunir a revisão das métricas de onboarding",
        "Corrida leve de 5 km",
        "Marcar consulta no dentista",
        "Dia disperso — as reuniões comeram a manhã. Planear o trabalho profundo mais cedo.",
        "A energia aguentou até à noite. A corrida dissipou o nevoeiro mental.",
        "Cumpri as três. Bom ritmo. O sono fez diferença.",
        "Perdi o ímpeto depois do almoço. Tentar um almoço mais leve.",
        "O melhor dia da semana. A manhã protegida compensou.",
        "Sólido. A preparação da conversa de carreira está a avançar.",
        "Ideia: juntar os recados ao sábado todas as semanas",
        "Juntar conservatória, lavandaria e loja de bricolage num só bloco ao sábado. Testar 3 semanas.",
        "Ver: palestra sobre padrões de navegação em SwiftUI",
        "Sessão da WWDC25 sobre navegação programática. Comparar NavigationStack e SplitView.",
        "Redesenho do onboarding — resumo de uma página",
        "Problema: 41 % dos novos utilizadores nunca chegam às Três Prioridades no primeiro dia. Hipótese: reduzir a escolha capturar/planear no dia 1. A variante A troca o estado vazio por 3 prioridades de exemplo.",
        "Preparar a conversa de carreira com a chefia",
        "Temas: alargamento do âmbito, mentoria dos novos colaboradores, alinhamento dos OKR do 1.º trimestre. Conquista para começar: A/B de onboarding lançado com +12 % de ativação.",
        "Conclusão: os blocos de trabalho profundo encolhem sem proteção",
        "Três semanas seguidas em que o Slack reativo quebrou os blocos da manhã — a produção caiu de forma mensurável. Marcar o bloco das 9h–11h como inamovível a partir da próxima semana.",
        "Dormi bem. Ligeiras dores da corrida de ontem.",
        "Corrida leve de 5,2 km, 27 min",
        "Ritmo constante, respiração controlada. Podia ter forçado no último km.",
        "Ioga: mobilidade da anca",
        "Ioga: mobilidade da anca (fluxo de 35 min)",
        "As ancas estão a abrir. Incluir duas vezes por semana em vez de uma.",
        "Preparação de refeições de domingo",
        "Planear o menu da semana",
        "Verificar a despensa + escrever a lista",
        "Fazer as compras em 60 min",
        "Cozinhar proteínas + cereais em grande quantidade",
        "Dividir os almoços por 5 recipientes",
        "Pôr a reciclagem na rua",
        "Pôr o caixote cá fora antes da recolha de terça às 6h.",
        "Repor o detergente da loiça",
        "Check-up semestral atrasado duas semanas.",
        "Nacional + regional. Vence no dia 15.",
        "A consistência na carreira subiu com manhãs protegidas; a energia caiu no dia com menos sono.",
        "Lançado o teste A/B do redesenho do onboarding",
        "Variante A (sugestões de prioridades no estado vazio) lançada a 50 % dos novos utilizadores. A ativação no dia 1 subiu +12 % face ao controlo nas primeiras 2000 coortes.",
        "+12 % de ativação; n=2134",
        "Liderei o arranque da migração com três equipas",
        "Backend, mobile e plataforma alinhados no plano de migração do esquema. Revistos o caminho de rollback, os responsáveis e os critérios de aceitação. Sem bloqueios à saída da reunião.",
        "3 equipas alinhadas; 0 bloqueios",
    ],
    "pt-BR": [
        "Finalizar as notas dos 1:1 do 4º trimestre",
        "Corrida leve de 30 min antes do jantar",
        "Pegar as roupas na lavanderia até as 18h",
        "Redigir os tópicos da retro da sprint",
        "Força: pernas (3×8)",
        "Pagar a estimativa de imposto trimestral",
        "Montar a revisão das métricas de onboarding",
        "Corrida leve de 5 km",
        "Agendar consulta no dentista",
        "Dia disperso — as reuniões comeram a manhã. Planejar o trabalho focado mais cedo.",
        "A energia se manteve até a noite. A corrida dissipou a névoa mental.",
        "Fiz as três. Bom ritmo. O sono fez diferença.",
        "Perdi o embalo depois do almoço. Tentar um almoço mais leve.",
        "O melhor dia da semana. A manhã protegida valeu a pena.",
        "Sólido. A preparação da conversa de carreira está avançando.",
        "Ideia: juntar as tarefas aos sábados toda semana",
        "Juntar Detran, lavanderia e loja de materiais em um único bloco no sábado. Testar por 3 semanas.",
        "Assistir: palestra sobre padrões de navegação no SwiftUI",
        "Sessão da WWDC25 sobre navegação programática. Comparar NavigationStack e SplitView.",
        "Redesenho do onboarding — resumo de uma página",
        "Problema: 41% dos novos usuários nunca chegam às Três Prioridades no primeiro dia. Hipótese: reduzir a escolha capturar/planejar no dia 1. A variante A troca o estado vazio por 3 prioridades de exemplo.",
        "Preparar a conversa de carreira com o gestor",
        "Tópicos: ampliação de escopo, mentoria dos novos contratados, alinhamento dos OKRs do 1º trimestre. Conquista para começar: A/B de onboarding lançado com +12% de ativação.",
        "Insight: os blocos de trabalho focado encolhem sem proteção",
        "Três semanas seguidas em que o Slack reativo quebrou os blocos da manhã — a produção caiu de forma mensurável. Marcar o bloco das 9h–11h como inamovível a partir da próxima semana.",
        "Dormi bem. Leve dor muscular da corrida de ontem.",
        "Corrida leve de 5,2 km, 27 min",
        "Ritmo constante, respiração sob controle. Dava para forçar no último km.",
        "Ioga: mobilidade do quadril",
        "Ioga: mobilidade do quadril (fluxo de 35 min)",
        "Os quadris estão abrindo. Incluir duas vezes por semana em vez de uma.",
        "Preparo de refeições de domingo",
        "Planejar o cardápio da semana",
        "Conferir a despensa + escrever a lista",
        "Fazer as compras em 60 min",
        "Cozinhar proteínas + grãos em grande quantidade",
        "Dividir os almoços em 5 potes",
        "Levar a reciclagem para fora",
        "Colocar a lixeira na rua antes da coleta de terça às 6h.",
        "Repor o detergente",
        "Check-up semestral atrasado duas semanas.",
        "Federal + estadual. Vence no dia 15.",
        "A consistência na carreira subiu com manhãs protegidas; a energia caiu no dia com menos sono.",
        "Teste A/B do redesenho do onboarding lançado",
        "Variante A (sugestões de prioridades no estado vazio) lançada para 50% dos novos usuários. A ativação no dia 1 subiu +12% em relação ao controle nas primeiras 2.000 coortes.",
        "+12% de ativação; n=2.134",
        "Liderei o kickoff da migração com três times",
        "Backend, mobile e plataforma alinhados no plano de migração do schema. Revisamos o caminho de rollback, os responsáveis e os critérios de aceite. Sem bloqueios ao sair da reunião.",
        "3 times alinhados; 0 bloqueios",
    ],
    "nl": [
        "1-op-1-notities Q4 afronden",
        "Rustige duurloop van 30 min voor het eten",
        "Stomerij ophalen vóór 18 uur",
        "Punten voor sprintretro opstellen",
        "Kracht: benen (3×8)",
        "Voorlopige kwartaalbelasting betalen",
        "Review van onboardingmetrics samenstellen",
        "Rustige duurloop van 5 km",
        "Afspraak bij de tandarts maken",
        "Versnipperde dag — vergaderingen aten de ochtend op. Diep werk eerder inplannen.",
        "Energie hield aan tot de avond. De duurloop verdreef de mentale mist.",
        "Alle drie gehaald. Goed ritme. Slaap deed ertoe.",
        "Na de lunch de vaart verloren. Lichtere lunch proberen.",
        "Beste dag deze week. De beschermde ochtend wierp vruchten af.",
        "Degelijk. De voorbereiding van het loopbaangesprek schiet op.",
        "Idee: boodschappen wekelijks op zaterdag bundelen",
        "Gemeente, stomerij en bouwmarkt in één zaterdagblok bundelen. 3 weken testen.",
        "Bekijken: talk over SwiftUI-navigatiepatronen",
        "WWDC25-sessie over programmatische navigatie. NavigationStack en SplitView afwegen.",
        "Herontwerp onboarding — onepager",
        "Probleem: 41% van de nieuwe gebruikers bereikt op dag één nooit de Focus Drie. Hypothese: de keuze vastleggen-of-plannen op dag 1 verminderen. Variant A vervangt de lege staat door 3 voorbeeldfocuspunten.",
        "Loopbaangesprek met leidinggevende voorbereiden",
        "Onderwerpen: uitbreiding van scope, mentorschap van nieuwe medewerkers, afstemming Q1-OKR's. Resultaat om mee te openen: onboarding-A/B uitgebracht met +12% activatie.",
        "Inzicht: blokken diep werk krimpen zonder bescherming",
        "Drie weken op rij waarin ochtendblokken door reactieve Slack werden verbroken — de output daalde meetbaar. Het blok van 9–11 uur vanaf volgende week als onverplaatsbaar inplannen.",
        "Goed geslapen. Lichte spierpijn van de duurloop van gisteren.",
        "Rustige duurloop van 5,2 km, 27 min",
        "Constant tempo, ademhaling onder controle. Had de laatste km kunnen pushen.",
        "Yoga: heupmobiliteit",
        "Yoga: heupmobiliteit (flow van 35 min)",
        "Heupen openen zich. Twee keer per week inbouwen in plaats van één.",
        "Maaltijdprep op zondag",
        "Menu voor de week plannen",
        "Voorraadkast inventariseren + lijst schrijven",
        "Binnen 60 min boodschappen doen",
        "Eiwitten + granen in bulk koken",
        "Lunches over 5 bakjes verdelen",
        "Recycling buitenzetten",
        "Bak buitenzetten vóór ophalen dinsdag 6 uur.",
        "Afwasmiddel bijvullen",
        "Halfjaarlijkse controle twee weken te laat.",
        "Landelijk + regionaal. Vervalt op de 15e.",
        "Loopbaanopvolging steeg met beschermde ochtendblokken; energie zakte op de dag met de minste slaap.",
        "A/B-test van onboardingherontwerp uitgebracht",
        "Variant A (voorbeeldfocussuggesties in de lege staat) uitgerold naar 50% van de nieuwe gebruikers. Activatie op dag 1 steeg +12% t.o.v. de controle over de eerste 2.000 cohorten.",
        "+12% activatie; n=2.134",
        "Migratie-kick-off met drie teams geleid",
        "Backend, mobile en platform afgestemd op het schema-migratieplan. Rollback-pad, eigenaren en acceptatiecriteria doorgenomen. Geen openstaande blokkades na de meeting.",
        "3 teams afgestemd; 0 blokkades",
    ],
    "sv": [
        "Slutför anteckningar från Q4-avstämningar",
        "Lugn löprunda 30 min före middagen",
        "Hämta kemtvätten före 18",
        "Skissa punkter till sprintretron",
        "Styrka: ben (3×8)",
        "Betala preliminärskatt för kvartalet",
        "Sammanställ genomgång av onboardingmått",
        "Lugn löprunda 5 km",
        "Boka tandläkartid",
        "Spretig dag – mötena åt upp morgonen. Planera djuparbete tidigare.",
        "Energin höll till kvällen. Löprundan skingrade dimman i huvudet.",
        "Klarade alla tre. Bra rytm. Sömnen spelade roll.",
        "Tappade fart efter lunch. Testa en lättare lunch.",
        "Veckans bästa dag. Den skyddade morgonen lönade sig.",
        "Stabilt. Förberedelsen inför karriärsamtalet ger resultat.",
        "Idé: samla ärenden på lördagar varje vecka",
        "Samla bilprov, kemtvätt och byggvaruhus i ett enda lördagspass. Testa i 3 veckor.",
        "Se: föredrag om navigeringsmönster i SwiftUI",
        "WWDC25-session om programmatisk navigering. Jämför NavigationStack och SplitView.",
        "Omdesign av onboarding – ettsidare",
        "Problem: 41 % av nya användare når aldrig Fokus tre dag ett. Hypotes: minska valet fånga-eller-planera dag 1. Variant A byter ut tomläget mot 3 exempel på fokuspunkter.",
        "Förbered karriärsamtal med chefen",
        "Ämnen: utökat ansvar, mentorskap för nyanställda, samordning av Q1-OKR. Framgång att inleda med: onboarding-A/B lanserad med +12 % aktivering.",
        "Insikt: block för djuparbete krymper utan skydd",
        "Tre veckor i rad då morgonblocken bröts av reaktivt Slack – produktionen sjönk mätbart. Boka blocket 9–11 som orubbligt från nästa vecka.",
        "Sov gott. Lätt träningsvärk efter gårdagens löprunda.",
        "Lugn löprunda 5,2 km, 27 min",
        "Jämnt tempo, andningen under kontroll. Kunde ha pressat sista kilometern.",
        "Yoga: höftrörlighet",
        "Yoga: höftrörlighet (35 min flow)",
        "Höfterna öppnar sig. Lägg in det två gånger i veckan i stället för en.",
        "Matlagning på söndagen",
        "Planera veckans meny",
        "Inventera skafferiet + skriv lista",
        "Handla inom 60 min",
        "Tillaga protein + spannmål i storkok",
        "Portionera luncher i 5 lådor",
        "Ta ut återvinningen",
        "Ställ ut kärlet före tömning tisdag kl. 6.",
        "Fyll på diskmedel",
        "Halvårskontroll två veckor försenad.",
        "Statlig + regional. Förfaller den 15:e.",
        "Karriärsuppföljningen ökade med skyddade morgnar; energin sjönk dagen med minst sömn.",
        "A/B-test för omdesignad onboarding lanserat",
        "Variant A (exempel på fokusförslag i tomläget) lanserad till 50 % av nya användare. Aktiveringen dag 1 steg +12 % mot kontrollen över de första 2 000 kohorterna.",
        "+12 % aktivering; n=2 134",
        "Ledde uppstart av migrering med tre team",
        "Backend, mobil och plattform samordnade kring schemamigreringsplanen. Gick igenom rollback-väg, ansvariga och acceptanskriterier. Inga öppna hinder efter mötet.",
        "3 team samordnade; 0 hinder",
    ],
    "nb": [
        "Fullføre notater fra Q4-en-til-en-møter",
        "Rolig løpetur på 30 min før middag",
        "Hente rensetøyet innen kl. 18",
        "Skissere punkter til sprintretroen",
        "Styrke: bein (3×8)",
        "Betale forskuddsskatt for kvartalet",
        "Sette sammen gjennomgang av onboarding-tall",
        "Rolig løpetur på 5 km",
        "Bestille time hos tannlegen",
        "Spredt dag – møtene spiste opp morgenen. Planlegg dyparbeid tidligere.",
        "Energien holdt til kvelden. Løpeturen fjernet tåka i hodet.",
        "Klarte alle tre. God rytme. Søvnen hadde noe å si.",
        "Mistet driv etter lunsj. Prøv en lettere lunsj.",
        "Ukas beste dag. Den skjermede morgenen lønte seg.",
        "Solid. Forberedelsen til karrieresamtalen gir resultater.",
        "Idé: samle ærender på lørdager hver uke",
        "Samle trafikkstasjon, renseri og byggevarehus i én lørdagsbolk. Test i 3 uker.",
        "Se: foredrag om navigasjonsmønstre i SwiftUI",
        "WWDC25-økt om programmatisk navigasjon. Sammenlikn NavigationStack og SplitView.",
        "Redesign av onboarding – ettsider",
        "Problem: 41 % av nye brukere når aldri Fokus tre den første dagen. Hypotese: reduser valget fang-eller-planlegg på dag 1. Variant A bytter ut tomtilstanden med 3 eksempelfokuspunkter.",
        "Forberede karrieresamtale med lederen",
        "Temaer: utvidet ansvar, mentorering av nyansatte, samkjøring av Q1-OK-er. Resultat å åpne med: onboarding-A/B lansert med +12 % aktivering.",
        "Innsikt: blokker for dyparbeid krymper uten beskyttelse",
        "Tre uker på rad der morgenblokkene ble brutt av reaktiv Slack – produksjonen falt målbart. Sett av blokken 9–11 som urokkelig fra neste uke.",
        "Sov godt. Lett stølhet etter gårsdagens løpetur.",
        "Rolig løpetur på 5,2 km, 27 min",
        "Jevnt tempo, pusten under kontroll. Kunne ha presset siste kilometer.",
        "Yoga: hoftemobilitet",
        "Yoga: hoftemobilitet (35 min flyt)",
        "Hoftene åpner seg. Legg det inn to ganger i uka i stedet for én.",
        "Måltidsforberedelse på søndag",
        "Planlegge ukas meny",
        "Sjekke matskapet + skrive liste",
        "Handle på 60 min",
        "Lage protein + korn i storkok",
        "Fordele lunsjer i 5 bokser",
        "Sette ut gjenvinningen",
        "Sett ut dunken før henting tirsdag kl. 6.",
        "Fylle på oppvasksåpe",
        "Halvårskontroll to uker på etterskudd.",
        "Statlig + regional. Forfaller den 15.",
        "Karriereoppfølgingen økte med skjermede morgener; energien falt dagen med minst søvn.",
        "A/B-test for redesignet onboarding lansert",
        "Variant A (eksempelfokusforslag i tomtilstanden) rullet ut til 50 % av nye brukere. Aktiveringen dag 1 økte +12 % mot kontrollen over de første 2000 kohortene.",
        "+12 % aktivering; n=2134",
        "Ledet oppstart av migrering med tre team",
        "Backend, mobil og plattform samkjørt om planen for skjemamigrering. Gikk gjennom rollback-vei, ansvarlige og akseptkriterier. Ingen åpne blokkeringer etter møtet.",
        "3 team samkjørt; 0 blokkeringer",
    ],
    "ru": [
        "Завершить заметки по встречам 1:1 за 4-й квартал",
        "Лёгкая пробежка 30 мин перед ужином",
        "Забрать вещи из химчистки до 18:00",
        "Набросать тезисы для ретро спринта",
        "Силовая: ноги (3×8)",
        "Внести квартальный авансовый налог",
        "Собрать обзор метрик онбординга",
        "Лёгкая пробежка 5 км",
        "Записаться к стоматологу",
        "День разбросанный — встречи съели всё утро. Планировать глубокую работу раньше.",
        "Энергии хватило до вечера. Пробежка развеяла туман в голове.",
        "Сделал все три. Хороший ритм. Сон сыграл роль.",
        "После обеда потерял темп. Попробовать более лёгкий обед.",
        "Лучший день недели. Защищённое утро себя оправдало.",
        "Стабильно. Подготовка к карьерному разговору движется.",
        "Идея: объединять дела по субботам каждую неделю",
        "Объединить ГАИ, химчистку и хозяйственный магазин в один субботний блок. Проверить 3 недели.",
        "Посмотреть: доклад о паттернах навигации в SwiftUI",
        "Сессия WWDC25 о программной навигации. Сравнить NavigationStack и SplitView.",
        "Редизайн онбординга — одностраничник",
        "Проблема: 41 % новых пользователей в первый день так и не доходят до «Трёх фокусов». Гипотеза: убрать выбор «записать или запланировать» в день 1. Вариант A заменяет пустое состояние тремя примерами фокусов.",
        "Подготовиться к карьерному разговору с руководителем",
        "Темы: расширение зоны ответственности, наставничество новичков, согласование OKR на 1-й квартал. Достижение для начала: запущен A/B онбординга с +12 % активации.",
        "Вывод: блоки глубокой работы сжимаются без защиты",
        "Три недели подряд утренние блоки рвал реактивный Slack — продуктивность заметно упала. Со следующей недели закрепить блок 9–11 как непереносимый.",
        "Выспался. Лёгкая крепатура после вчерашней пробежки.",
        "Лёгкая пробежка 5,2 км, 27 мин",
        "Ровный темп, дыхание под контролем. Мог бы прибавить на последнем км.",
        "Йога: подвижность бёдер",
        "Йога: подвижность бёдер (поток 35 мин)",
        "Бёдра раскрываются. Добавить дважды в неделю вместо одного.",
        "Воскресная заготовка еды",
        "Спланировать меню на неделю",
        "Проверить запасы + составить список",
        "Закупиться за 60 мин",
        "Приготовить белки + крупы впрок",
        "Разложить обеды по 5 контейнерам",
        "Вынести вторсырьё",
        "Выставить бак до вывоза во вторник в 6 утра.",
        "Пополнить средство для мытья посуды",
        "Полугодовой осмотр просрочен на две недели.",
        "Федеральный + региональный. Срок до 15-го.",
        "Последовательность в карьере выросла с защищёнными утрами; энергия упала в день с наименьшим сном.",
        "Запущен A/B-тест редизайна онбординга",
        "Вариант A (примеры фокусов в пустом состоянии) выкатили на 50 % новых пользователей. Активация в день 1 выросла на +12 % к контролю на первых 2000 когортах.",
        "+12 % активации; n=2134",
        "Провёл запуск миграции с тремя командами",
        "Согласовал бэкенд, мобайл и платформу по плану миграции схемы. Разобрали путь отката, ответственных и критерии приёмки. После встречи открытых блокеров нет.",
        "3 команды согласованы; 0 блокеров",
    ],
    "uk": [
        "Завершити нотатки зі зустрічей 1:1 за 4-й квартал",
        "Легка пробіжка 30 хв перед вечерею",
        "Забрати речі з хімчистки до 18:00",
        "Накидати тези для ретро спринту",
        "Силова: ноги (3×8)",
        "Сплатити квартальний авансовий податок",
        "Зібрати огляд метрик онбордингу",
        "Легка пробіжка 5 км",
        "Записатися до стоматолога",
        "День розпорошений — зустрічі з’їли весь ранок. Планувати глибоку роботу раніше.",
        "Енергії вистачило до вечора. Пробіжка розвіяла туман у голові.",
        "Зробив усі три. Гарний ритм. Сон мав значення.",
        "Після обіду втратив темп. Спробувати легший обід.",
        "Найкращий день тижня. Захищений ранок себе виправдав.",
        "Стабільно. Підготовка до кар’єрної розмови просувається.",
        "Ідея: об’єднувати справи щосуботи щотижня",
        "Об’єднати сервісний центр, хімчистку та будівельний магазин в один суботній блок. Перевірити 3 тижні.",
        "Переглянути: доповідь про патерни навігації в SwiftUI",
        "Сесія WWDC25 про програмну навігацію. Порівняти NavigationStack і SplitView.",
        "Редизайн онбордингу — односторінківка",
        "Проблема: 41 % нових користувачів першого дня так і не доходять до «Трьох фокусів». Гіпотеза: прибрати вибір «записати чи запланувати» в день 1. Варіант A замінює порожній стан трьома прикладами фокусів.",
        "Підготуватися до кар’єрної розмови з керівником",
        "Теми: розширення зони відповідальності, менторство новачків, узгодження OKR на 1-й квартал. Досягнення для початку: запущено A/B онбордингу з +12 % активації.",
        "Висновок: блоки глибокої роботи стискаються без захисту",
        "Три тижні поспіль ранкові блоки рвав реактивний Slack — продуктивність помітно впала. З наступного тижня закріпити блок 9–11 як непорушний.",
        "Виспався. Легка крепатура після вчорашньої пробіжки.",
        "Легка пробіжка 5,2 км, 27 хв",
        "Рівний темп, дихання під контролем. Міг би додати на останньому км.",
        "Йога: рухливість стегон",
        "Йога: рухливість стегон (потік 35 хв)",
        "Стегна розкриваються. Додати двічі на тиждень замість одного.",
        "Недільна заготівля їжі",
        "Спланувати меню на тиждень",
        "Перевірити запаси + скласти список",
        "Закупитися за 60 хв",
        "Приготувати білки + крупи про запас",
        "Розкласти обіди по 5 контейнерах",
        "Винести вторсировину",
        "Виставити бак до вивозу у вівторок о 6 ранку.",
        "Поповнити засіб для миття посуду",
        "Піврічний огляд прострочено на два тижні.",
        "Федеральний + регіональний. Термін до 15-го.",
        "Послідовність у кар’єрі зросла із захищеними ранками; енергія впала в день із найменшим сном.",
        "Запущено A/B-тест редизайну онбордингу",
        "Варіант A (приклади фокусів у порожньому стані) розгорнули на 50 % нових користувачів. Активація в день 1 зросла на +12 % до контролю на перших 2000 когортах.",
        "+12 % активації; n=2134",
        "Провів запуск міграції з трьома командами",
        "Узгодив бекенд, мобайл і платформу щодо плану міграції схеми. Розібрали шлях відкату, відповідальних і критерії приймання. Після зустрічі відкритих блокерів немає.",
        "3 команди узгоджено; 0 блокерів",
    ],
    "tr": [
        "Q4 birebir görüşme notlarını tamamla",
        "Akşam yemeğinden önce 30 dk hafif koşu",
        "Kuru temizlemeyi 18:00'a kadar al",
        "Sprint retro maddelerini taslak yap",
        "Kuvvet: bacak (3×8)",
        "Üç aylık geçici vergiyi öde",
        "Onboarding metrik değerlendirmesini derle",
        "5 km hafif koşu",
        "Diş hekiminden randevu al",
        "Dağınık bir gün — toplantılar sabahı yedi. Derin çalışmayı daha erkene planla.",
        "Enerji akşama kadar dayandı. Koşu zihnimdeki sisi dağıttı.",
        "Üçünü de yaptım. İyi tempo. Uyku fark yarattı.",
        "Öğle yemeğinden sonra ivme kayboldu. Daha hafif bir öğle yemeği dene.",
        "Haftanın en iyi günü. Korunan sabah işe yaradı.",
        "Sağlam. Kariyer görüşmesi hazırlığı ilerliyor.",
        "Fikir: işleri her hafta cumartesi toplu yap",
        "Trafik müdürlüğü, kuru temizleme ve hırdavatçıyı tek bir cumartesi bloğunda topla. 3 hafta dene.",
        "İzle: SwiftUI navigasyon desenleri konuşması",
        "Programatik navigasyon üzerine WWDC25 oturumu. NavigationStack ile SplitView'ı karşılaştır.",
        "Onboarding yeniden tasarımı — tek sayfalık özet",
        "Sorun: yeni kullanıcıların %41'i ilk gün Üç Odak'a hiç ulaşmıyor. Hipotez: 1. günde yakala-mı-planla-mı seçimini azalt. A varyantı boş durumu 3 örnek odak maddesiyle değiştiriyor.",
        "Yöneticiyle kariyer görüşmesine hazırlan",
        "Konular: kapsam genişletme, yeni işe alımlara mentorluk, Q1 OKR uyumu. Açılışta öne çıkar: +%12 aktivasyonla yayınlanan onboarding A/B'si.",
        "İçgörü: derin çalışma blokları korunmazsa küçülür",
        "Üç hafta üst üste sabah blokları tepkisel Slack yüzünden bölündü — üretim ölçülebilir biçimde düştü. Gelecek haftadan itibaren 9–11 bloğunu taşınamaz olarak takvime koy.",
        "İyi uyudum. Dünkü koşudan hafif kas ağrısı.",
        "5,2 km hafif koşu, 27 dk",
        "Sabit tempo, nefes kontrol altında. Son kilometrede daha fazla zorlayabilirdim.",
        "Yoga: kalça hareketliliği",
        "Yoga: kalça hareketliliği (35 dk akış)",
        "Kalçalar açılıyor. Haftada bir yerine iki kez ekle.",
        "Pazar günü yemek hazırlığı",
        "Haftanın menüsünü planla",
        "Kileri gözden geçir + liste yaz",
        "60 dk içinde alışveriş yap",
        "Protein + tahılları toplu pişir",
        "Öğle yemeklerini 5 kaba böl",
        "Geri dönüşümü çıkar",
        "Salı sabah 6 toplamadan önce çöpü dışarı çıkar.",
        "Bulaşık deterjanını doldur",
        "Altı aylık kontrol iki hafta gecikti.",
        "Federal + eyalet. Son tarih ayın 15'i.",
        "Korunan sabah bloklarıyla kariyer takibi arttı; en az uyunan günde enerji düştü.",
        "Onboarding yeniden tasarımı A/B testi yayınlandı",
        "A varyantı (boş durumda örnek odak önerileri) yeni kullanıcıların %50'sine sunuldu. İlk 2.000 kohortta 1. gün aktivasyonu kontrole göre +%12 arttı.",
        "+%12 aktivasyon; n=2.134",
        "Üç ekiple migrasyon başlangıcını yönettim",
        "Backend, mobil ve platformu şema migrasyon planında hizaladım. Geri alma yolunu, sorumluları ve kabul kriterlerini gözden geçirdik. Toplantı çıkışında açık engel yok.",
        "3 ekip hizalandı; 0 engel",
    ],
    "ja": [
        "Q4の1on1メモを仕上げる",
        "夕食前に30分の軽いラン",
        "18時までにクリーニングを受け取る",
        "スプリントレトロの論点をまとめる",
        "筋力：脚（3×8）",
        "四半期の予定納税を支払う",
        "オンボーディング指標レビューをまとめる",
        "5kmの軽いラン",
        "歯医者の予約を取る",
        "散漫な一日——会議で午前が消えた。ディープワークをもっと早く計画する。",
        "夜までエネルギーが続いた。ランで頭の靄が晴れた。",
        "3つとも達成。良いリズム。睡眠が効いた。",
        "昼食後に勢いを失った。昼を軽めにしてみる。",
        "今週一番の日。守った午前が報われた。",
        "順調。キャリア面談の準備が効いてきた。",
        "アイデア：土曜に用事を毎週まとめる",
        "陸運局・クリーニング・ホームセンターを土曜の一枠にまとめる。3週間試す。",
        "視聴：SwiftUIのナビゲーションパターンの講演",
        "プログラムによるナビゲーションのWWDC25セッション。NavigationStackとSplitViewを比較。",
        "オンボーディング再設計——1ページ概要",
        "課題：新規ユーザーの41%が初日に「フォーカス3」へ到達しない。仮説：初日の「記録か計画か」の選択を減らす。バリアントAは空状態を3つのサンプルフォーカスに差し替える。",
        "上司とのキャリア面談の準備",
        "テーマ：担当範囲の拡大、新人のメンタリング、Q1 OKRのすり合わせ。冒頭で出す成果：+12%の活性化でオンボーディングA/Bをリリース。",
        "気づき：ディープワークの枠は守らないと縮む",
        "3週連続で午前の枠が受け身のSlackに崩された——アウトプットが目に見えて低下。来週から9〜11時の枠を動かせない予定として確保する。",
        "よく眠れた。昨日のランで軽い筋肉痛。",
        "5.2kmの軽いラン、27分",
        "一定のペース、呼吸も安定。最後の1kmはもっと押せた。",
        "ヨガ：股関節モビリティ",
        "ヨガ：股関節モビリティ（35分フロー）",
        "股関節が開いてきた。週1ではなく週2に増やす。",
        "日曜の作り置き",
        "今週の献立を計画する",
        "パントリーを確認＋リスト作成",
        "60分以内に買い物",
        "タンパク質＋主食をまとめて調理",
        "昼食を5つの容器に小分け",
        "資源ごみを出す",
        "火曜午前6時の収集前にゴミ箱を出す。",
        "食器用洗剤を補充",
        "半年検診が2週間遅れ。",
        "連邦＋州。期限は15日。",
        "午前の枠を守るとキャリアの継続が伸びた一方、睡眠が最も短い日にエネルギーが落ちた。",
        "オンボーディング再設計のA/Bテストをリリース",
        "バリアントA（空状態のサンプルフォーカス提案）を新規ユーザーの50%に展開。最初の2,000コホートで初日活性化が対照比+12%。",
        "+12%活性化；n=2,134",
        "3チームでマイグレーションのキックオフを主導",
        "バックエンド・モバイル・基盤をスキーマ移行計画で合意。ロールバック手順、担当者、受け入れ基準を確認。会議終了時点で未解決のブロッカーなし。",
        "3チーム合意；ブロッカー0",
    ],
    "ko": [
        "4분기 1:1 노트 마무리하기",
        "저녁 전 30분 가벼운 러닝",
        "18시까지 세탁물 찾기",
        "스프린트 회고 논점 정리하기",
        "근력: 다리 (3×8)",
        "분기 예정 세금 납부",
        "온보딩 지표 리뷰 취합하기",
        "5km 가벼운 러닝",
        "치과 예약 잡기",
        "산만한 하루 — 회의가 오전을 잡아먹음. 딥워크를 더 일찍 계획하기.",
        "에너지가 저녁까지 유지됨. 러닝이 머릿속 안개를 걷어냄.",
        "세 개 다 완료. 리듬 좋음. 수면이 중요했음.",
        "점심 후 추진력 상실. 더 가벼운 점심 시도.",
        "이번 주 최고의 날. 지킨 오전이 보답함.",
        "탄탄함. 커리어 면담 준비가 효과를 봄.",
        "아이디어: 토요일마다 볼일을 한 번에 모으기",
        "차량등록소·세탁소·철물점을 토요일 한 블록으로 묶기. 3주간 테스트.",
        "보기: SwiftUI 내비게이션 패턴 강연",
        "프로그래매틱 내비게이션 WWDC25 세션. NavigationStack과 SplitView 비교.",
        "온보딩 리디자인 — 한 장 요약",
        "문제: 신규 사용자의 41%가 첫날 '포커스 셋'에 도달하지 못함. 가설: 1일 차의 캡처-대-계획 선택을 줄이기. 변형 A는 빈 상태를 샘플 포커스 3개로 교체.",
        "관리자와의 커리어 면담 준비",
        "주제: 역할 확대, 신규 입사자 멘토링, 1분기 OKR 정렬. 먼저 꺼낼 성과: +12% 활성화로 온보딩 A/B 출시.",
        "인사이트: 딥워크 블록은 보호하지 않으면 줄어든다",
        "3주 연속 오전 블록이 즉각 대응형 Slack에 깨짐 — 산출물이 눈에 띄게 감소. 다음 주부터 9~11시 블록을 옮길 수 없는 일정으로 확보.",
        "잘 잤음. 어제 러닝으로 가벼운 근육통.",
        "5.2km 가벼운 러닝, 27분",
        "일정한 페이스, 호흡 안정. 마지막 1km는 더 밀어붙일 수 있었음.",
        "요가: 고관절 가동성",
        "요가: 고관절 가동성 (35분 플로우)",
        "고관절이 열리는 중. 주 1회 대신 주 2회로 추가.",
        "일요일 식단 준비",
        "이번 주 메뉴 계획",
        "팬트리 점검 + 목록 작성",
        "60분 안에 장보기",
        "단백질 + 곡물 대량 조리",
        "점심을 5개 용기에 나누기",
        "재활용 내놓기",
        "화요일 오전 6시 수거 전에 통 내놓기.",
        "주방세제 리필",
        "반기 검진이 2주 연체됨.",
        "연방 + 주. 15일 마감.",
        "오전 블록을 지키니 커리어 실행력이 올랐고, 수면이 가장 적었던 날 에너지가 떨어짐.",
        "온보딩 리디자인 A/B 테스트 출시",
        "변형 A(빈 상태의 샘플 포커스 제안)를 신규 사용자 50%에 배포. 첫 2,000개 코호트에서 1일 차 활성화가 대조군 대비 +12% 상승.",
        "+12% 활성화; n=2,134",
        "세 팀과 마이그레이션 킥오프 주도",
        "백엔드·모바일·플랫폼을 스키마 마이그레이션 계획에 정렬. 롤백 경로, 담당자, 승인 기준을 검토. 회의 종료 시점에 미해결 블로커 없음.",
        "3개 팀 정렬; 블로커 0",
    ],
    "zh-Hans": [
        "完成 Q4 一对一会议记录",
        "晚饭前 30 分钟轻松跑",
        "18 点前取干洗",
        "起草冲刺复盘要点",
        "力量：腿（3×8）",
        "缴纳季度预缴税",
        "整理入门指标回顾",
        "5 公里轻松跑",
        "预约牙医",
        "一天很零散——会议吃掉了上午。把深度工作安排得更早。",
        "精力维持到晚上。跑步驱散了脑中的迷雾。",
        "三项都完成。节奏不错。睡眠很关键。",
        "午饭后失去势头。试试更清淡的午餐。",
        "本周最好的一天。守住的上午有回报。",
        "稳。职业谈话的准备开始见效。",
        "想法：每周六把杂事集中处理",
        "把车管所、干洗店、五金店并到一个周六时段。试 3 周。",
        "观看：SwiftUI 导航模式的演讲",
        "关于程序化导航的 WWDC25 专题。比较 NavigationStack 与 SplitView。",
        "入门流程重新设计——一页纸",
        "问题：41% 的新用户第一天从未到达「三件要事」。假设：减少第 1 天「记录还是计划」的选择。变体 A 用 3 个示例要事替换空状态。",
        "准备与经理的职业谈话",
        "主题：扩大职责范围、指导新员工、对齐 Q1 OKR。开场亮点：上线入门 A/B，激活率 +12%。",
        "洞察：深度工作时段若不保护就会缩水",
        "连续三周上午时段被随到随处理的 Slack 打断——产出明显下降。从下周起把 9–11 点设为不可挪动的时段。",
        "睡得好。昨天跑步后轻微酸痛。",
        "5.2 公里轻松跑，27 分钟",
        "配速稳定，呼吸可控。最后一公里本可再加速。",
        "瑜伽：髋部灵活性",
        "瑜伽：髋部灵活性（35 分钟流程）",
        "髋部在打开。改为每周两次而非一次。",
        "周日备餐",
        "规划本周菜单",
        "盘点食品柜 + 写清单",
        "60 分钟内采购完",
        "批量烹饪蛋白质 + 主食",
        "把午餐分装到 5 个容器",
        "把可回收物拿出去",
        "周二早 6 点收运前把垃圾桶推出去。",
        "补充洗洁精",
        "半年体检逾期两周。",
        "联邦 + 州。15 号到期。",
        "守住上午时段后职业上的执行力提升；睡眠最少的那天精力下降。",
        "上线入门流程重新设计的 A/B 测试",
        "变体 A（空状态下的示例要事建议）已向 50% 的新用户发布。前 2,000 个群组中，第 1 天激活率较对照组 +12%。",
        "激活率 +12%；n=2,134",
        "带领三个团队启动迁移",
        "就架构迁移计划对齐了后端、移动端和平台。梳理了回滚路径、负责人和验收标准。散会时没有未决阻塞项。",
        "3 个团队已对齐；0 阻塞项",
    ],
    "zh-Hant": [
        "完成 Q4 一對一會議記錄",
        "晚餐前 30 分鐘輕鬆跑",
        "18 點前取乾洗",
        "草擬衝刺回顧要點",
        "力量：腿（3×8）",
        "繳納季度預繳稅",
        "彙整新手引導指標回顧",
        "5 公里輕鬆跑",
        "預約牙醫",
        "一天很零散——會議吃掉了上午。把深度工作安排得更早。",
        "精力維持到晚上。跑步驅散了腦中的迷霧。",
        "三項都完成。節奏不錯。睡眠很關鍵。",
        "午餐後失去動力。試試更清淡的午餐。",
        "本週最好的一天。守住的上午有回報。",
        "穩。職涯談話的準備開始見效。",
        "想法：每週六把雜事集中處理",
        "把監理站、乾洗店、五金行併到一個週六時段。試 3 週。",
        "觀看：SwiftUI 導覽模式的演講",
        "關於程式化導覽的 WWDC25 議程。比較 NavigationStack 與 SplitView。",
        "新手引導重新設計——一頁紙",
        "問題：41% 的新使用者第一天從未到達「三件要事」。假設：減少第 1 天「記錄還是規劃」的選擇。變體 A 用 3 個範例要事取代空狀態。",
        "準備與主管的職涯談話",
        "主題：擴大職責範圍、指導新進員工、對齊 Q1 OKR。開場亮點：上線新手引導 A/B，啟用率 +12%。",
        "洞察：深度工作時段若不保護就會縮水",
        "連續三週上午時段被隨到隨處理的 Slack 打斷——產出明顯下降。從下週起把 9–11 點設為不可挪動的時段。",
        "睡得好。昨天跑步後輕微痠痛。",
        "5.2 公里輕鬆跑，27 分鐘",
        "配速穩定，呼吸可控。最後一公里本可再加速。",
        "瑜伽：髖部靈活度",
        "瑜伽：髖部靈活度（35 分鐘流程）",
        "髖部在打開。改為每週兩次而非一次。",
        "週日備餐",
        "規劃本週菜單",
        "盤點食物櫃 + 寫清單",
        "60 分鐘內採購完",
        "大量烹調蛋白質 + 主食",
        "把午餐分裝到 5 個容器",
        "把可回收物拿出去",
        "週二早 6 點收運前把垃圾桶推出去。",
        "補充洗碗精",
        "半年體檢逾期兩週。",
        "聯邦 + 州。15 號到期。",
        "守住上午時段後職涯上的執行力提升；睡眠最少的那天精力下降。",
        "上線新手引導重新設計的 A/B 測試",
        "變體 A（空狀態下的範例要事建議）已向 50% 的新使用者發布。前 2,000 個群組中，第 1 天啟用率較對照組 +12%。",
        "啟用率 +12%；n=2,134",
        "帶領三個團隊啟動遷移",
        "就結構描述遷移計畫對齊了後端、行動端與平台。梳理了回復路徑、負責人與驗收標準。散會時沒有未決的阻礙項。",
        "3 個團隊已對齊；0 阻礙項",
    ],
    "ar": [
        "إنهاء ملاحظات اجتماعات الربع الرابع الفردية",
        "جري خفيف 30 دقيقة قبل العشاء",
        "استلام الملابس من المغسلة قبل الـ 6 مساءً",
        "صياغة نقاط مراجعة السبرنت",
        "قوة: الأرجل (3×8)",
        "دفع الدفعة الضريبية الربع سنوية",
        "تجميع مراجعة مقاييس الإعداد",
        "جري خفيف 5 كم",
        "حجز موعد طبيب الأسنان",
        "يوم مشتت — الاجتماعات التهمت الصباح. خطّط للعمل العميق مبكرًا.",
        "بقيت الطاقة حتى المساء. الجري بدّد الضباب الذهني.",
        "أنجزت الثلاثة. إيقاع جيد. النوم أحدث فرقًا.",
        "فقدت الزخم بعد الغداء. جرّب غداءً أخف.",
        "أفضل يوم هذا الأسبوع. الصباح المحمي أتى بثماره.",
        "متين. التحضير لحديث المسار المهني يتقدم.",
        "فكرة: تجميع المهام كل سبت أسبوعيًا",
        "اجمع إدارة المرور والمغسلة ومتجر الأدوات في كتلة واحدة يوم السبت. جرّب 3 أسابيع.",
        "للمشاهدة: محاضرة عن أنماط التنقل في SwiftUI",
        "جلسة WWDC25 عن التنقل البرمجي. قارن بين NavigationStack وSplitView.",
        "إعادة تصميم الإعداد — ملخص بصفحة واحدة",
        "المشكلة: 41% من المستخدمين الجدد لا يصلون أبدًا إلى «التركيزات الثلاثة» في اليوم الأول. الفرضية: تقليل خيار الالتقاط مقابل التخطيط في اليوم 1. النسخة A تستبدل الحالة الفارغة بثلاثة أمثلة تركيز.",
        "التحضير لحديث المسار المهني مع المدير",
        "المواضيع: توسيع النطاق، إرشاد الموظفين الجدد، مواءمة أهداف الربع الأول. الإنجاز للبدء به: إطلاق اختبار A/B للإعداد بزيادة تفعيل +12%.",
        "استنتاج: كتل العمل العميق تتقلص دون حماية",
        "ثلاثة أسابيع متتالية تكسّرت فيها كتل الصباح بسبب Slack التفاعلي — انخفض الإنتاج بشكل ملموس. ابتداءً من الأسبوع المقبل ثبّت كتلة 9–11 باعتبارها غير قابلة للنقل.",
        "نمت جيدًا. ألم عضلي خفيف من جري الأمس.",
        "جري خفيف 5.2 كم، 27 دقيقة",
        "وتيرة ثابتة، التنفس تحت السيطرة. كان بإمكاني الدفع في الكيلومتر الأخير.",
        "يوغا: مرونة الورك",
        "يوغا: مرونة الورك (تدفق 35 دقيقة)",
        "الوركان ينفتحان. أضِفها مرتين أسبوعيًا بدل مرة.",
        "تحضير وجبات الأحد",
        "تخطيط قائمة الأسبوع",
        "جرد المؤن + كتابة القائمة",
        "التسوق خلال 60 دقيقة",
        "طهي البروتينات + الحبوب بكميات كبيرة",
        "تقسيم وجبات الغداء على 5 علب",
        "إخراج إعادة التدوير",
        "أخرِج الحاوية قبل جمع الثلاثاء الساعة 6 صباحًا.",
        "إعادة تعبئة سائل غسل الأطباق",
        "فحص نصف سنوي متأخر أسبوعين.",
        "اتحادي + ولائي. الاستحقاق في الـ 15.",
        "ارتفع الالتزام المهني مع حماية صباحات العمل؛ وانخفضت الطاقة في اليوم الأقل نومًا.",
        "إطلاق اختبار A/B لإعادة تصميم الإعداد",
        "أُطلقت النسخة A (اقتراحات تركيز نموذجية في الحالة الفارغة) لـ 50% من المستخدمين الجدد. ارتفع تفعيل اليوم الأول بمقدار +12% مقارنة بالضابطة عبر أول 2000 مجموعة.",
        "تفعيل +12%؛ n=2134",
        "قُدت انطلاقة الترحيل مع ثلاثة فرق",
        "واءمت الواجهة الخلفية والموبايل والمنصة على خطة ترحيل المخطط. راجعنا مسار التراجع والمسؤولين ومعايير القبول. لا عوائق مفتوحة عند الخروج من الاجتماع.",
        "3 فرق متوائمة؛ 0 عوائق",
    ],
    "vi": [
        "Hoàn thiện ghi chú họp 1:1 quý 4",
        "Chạy nhẹ 30 phút trước bữa tối",
        "Lấy đồ giặt khô trước 18 giờ",
        "Soạn các điểm chính cho buổi retro sprint",
        "Sức mạnh: chân (3×8)",
        "Nộp thuế tạm tính theo quý",
        "Tổng hợp bản đánh giá chỉ số onboarding",
        "Chạy nhẹ 5 km",
        "Đặt lịch hẹn nha sĩ",
        "Một ngày phân tán — các cuộc họp ngốn hết buổi sáng. Lên lịch làm việc chuyên sâu sớm hơn.",
        "Năng lượng giữ được đến tối. Buổi chạy xua tan sương mù trong đầu.",
        "Làm xong cả ba. Nhịp tốt. Giấc ngủ có vai trò.",
        "Mất đà sau bữa trưa. Thử bữa trưa nhẹ hơn.",
        "Ngày tốt nhất tuần này. Buổi sáng được bảo vệ đã có kết quả.",
        "Vững. Việc chuẩn bị cho buổi trò chuyện nghề nghiệp đang tiến triển.",
        "Ý tưởng: gộp việc vặt vào thứ Bảy hằng tuần",
        "Gộp đăng kiểm, giặt khô và cửa hàng kim khí vào một khung thứ Bảy. Thử 3 tuần.",
        "Xem: bài nói về các mẫu điều hướng SwiftUI",
        "Phiên WWDC25 về điều hướng bằng mã. So sánh NavigationStack với SplitView.",
        "Thiết kế lại onboarding — bản tóm tắt một trang",
        "Vấn đề: 41% người dùng mới không bao giờ đến được «Ba ưu tiên» trong ngày đầu. Giả thuyết: giảm lựa chọn ghi-lại-hay-lên-kế-hoạch trong ngày 1. Biến thể A thay trạng thái trống bằng 3 ưu tiên mẫu.",
        "Chuẩn bị buổi trò chuyện nghề nghiệp với quản lý",
        "Chủ đề: mở rộng phạm vi, dìu dắt người mới, căn chỉnh OKR quý 1. Thành tích mở đầu: ra mắt A/B onboarding với +12% kích hoạt.",
        "Nhận định: các khối làm việc chuyên sâu co lại nếu không được bảo vệ",
        "Ba tuần liên tiếp các khối buổi sáng bị Slack phản ứng tức thời làm gãy — sản lượng giảm rõ rệt. Từ tuần sau, đặt khối 9–11 giờ là bất di bất dịch.",
        "Ngủ ngon. Hơi đau cơ nhẹ sau buổi chạy hôm qua.",
        "Chạy nhẹ 5,2 km, 27 phút",
        "Nhịp đều, kiểm soát hơi thở. Lẽ ra có thể bứt tốc ở km cuối.",
        "Yoga: linh hoạt hông",
        "Yoga: linh hoạt hông (chuỗi 35 phút)",
        "Hông đang mở ra. Tăng lên hai lần mỗi tuần thay vì một.",
        "Chuẩn bị bữa ăn ngày Chủ nhật",
        "Lên thực đơn cho tuần",
        "Kiểm kê tủ thực phẩm + viết danh sách",
        "Đi chợ trong 60 phút",
        "Nấu sẵn nhiều protein + ngũ cốc",
        "Chia bữa trưa vào 5 hộp",
        "Mang rác tái chế ra ngoài",
        "Đưa thùng rác ra trước giờ thu gom 6 giờ sáng thứ Ba.",
        "Đổ thêm nước rửa chén",
        "Khám định kỳ nửa năm trễ hai tuần.",
        "Liên bang + tiểu bang. Hạn ngày 15.",
        "Sự kiên trì với nghề nghiệp tăng nhờ giữ được các buổi sáng; năng lượng giảm vào ngày ngủ ít nhất.",
        "Đã ra mắt thử nghiệm A/B thiết kế lại onboarding",
        "Biến thể A (gợi ý ưu tiên mẫu ở trạng thái trống) đã triển khai cho 50% người dùng mới. Kích hoạt ngày 1 tăng +12% so với nhóm đối chứng trên 2.000 cohort đầu tiên.",
        "+12% kích hoạt; n=2.134",
        "Dẫn dắt khởi động di trú với ba nhóm",
        "Đã căn chỉnh backend, mobile và nền tảng theo kế hoạch di trú schema. Đã rà soát đường rollback, người phụ trách và tiêu chí nghiệm thu. Không còn vướng mắc nào khi kết thúc cuộc họp.",
        "3 nhóm đã căn chỉnh; 0 vướng mắc",
    ],
}


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(locale: str) -> tuple[int, int]:
    table = TRANSLATIONS.get(locale)
    if table is not None and len(table) != len(SOURCE):
        raise SystemExit(f"{locale}: {len(table)} translations != {len(SOURCE)} source keys")
    header = "English source." if locale == "en" else "LLM-drafted; blank entries fall back to English."
    lines = [
        f"/* MarketingSeed.strings — {locale}",
        "   DEBUG-only marketing screenshot seed copy used by OwloryUITestSupport.seedMarketing.",
        "   Generated by Tools/marketing-seed-strings-generate.py. NOT part of the",
        "   Localizable.strings UI catalog or its native-review pipeline.",
        f"   {header} */",
        "",
    ]
    translated = 0
    for i, key in enumerate(SOURCE):
        if locale == "en":
            value = key
        else:
            cand = table[i].strip() if table else ""
            value = cand or key
            translated += 1 if cand else 0
        lines.append(f'"{escape(key)}" = "{escape(value)}";')
    out = RESOURCES / f"{locale}.lproj" / "MarketingSeed.strings"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(SOURCE), (len(SOURCE) if locale == "en" else translated)


def main() -> None:
    for locale in LOCALES:
        n, translated = emit(locale)
        print(f"  {locale:8} {n} keys ({translated} translated)")
    print(f"\nWrote MarketingSeed.strings for {len(LOCALES)} locales ({len(SOURCE)} keys each).")


if __name__ == "__main__":
    main()
